version: '3'

services:
   db:
     image: mysql:8.0
     platform: linux/x86_64
     ports:
      - "9999:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:5.9
     ports:
       - "8000:80"
     volumes:
       - wp-data:/var/www/html
       - ./.htaccess:/var/www/html/.htaccess
       - ./wp-content/themes:/var/www/html/wp-content/themes
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DEBUG: 1
volumes:
    db_data:
    wp-data:
